spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: projektinzynierski13102023@gmail.com
    password: tznl vnrt nxnr ayxw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        default_schema: pchysioterapist
  flyway:
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password
    schemas: pchysioterapist

server:
  port: 8080