spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=floralstudio
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: floralstudio
  flyway:
    baseline-on-migrate: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password
    schemas: floralstudio

server:
  port: 8080