spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true;
        default_schema: pchysioterapist
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password
    schemas: pchysioterapist
    locations: classpath:db/migration
server:
  port: 8080